"""add server channel messages

Revision ID: 90878d18dc71
Revises: b85a9ddfaf2b
Create Date: 2026-05-04 16:16:04.842430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90878d18dc71"
down_revision: Union[str, Sequence[str], None] = "b85a9ddfaf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_channel_messages",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.String(length=255), nullable=True),
        sa.Column("message_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("text_preview", sa.Text(), nullable=True),
        sa.Column("thread_root_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["server_channels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_root_message_id"],
            ["server_channel_messages.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_server_channel_messages_author_user_id"),
        "server_channel_messages",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channel_messages_channel_id"),
        "server_channel_messages",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        "ix_server_channel_messages_channel_id_created_at_id",
        "server_channel_messages",
        ["channel_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channel_messages_message_type"),
        "server_channel_messages",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channel_messages_thread_root_message_id"),
        "server_channel_messages",
        ["thread_root_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_server_channel_messages_thread_root_message_id_created_at",
        "server_channel_messages",
        ["thread_root_message_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_server_channel_messages_thread_root_message_id_created_at",
        table_name="server_channel_messages",
    )
    op.drop_index(
        op.f("ix_server_channel_messages_thread_root_message_id"),
        table_name="server_channel_messages",
    )
    op.drop_index(
        op.f("ix_server_channel_messages_message_type"),
        table_name="server_channel_messages",
    )
    op.drop_index(
        "ix_server_channel_messages_channel_id_created_at_id",
        table_name="server_channel_messages",
    )
    op.drop_index(
        op.f("ix_server_channel_messages_channel_id"),
        table_name="server_channel_messages",
    )
    op.drop_index(
        op.f("ix_server_channel_messages_author_user_id"),
        table_name="server_channel_messages",
    )
    op.drop_table("server_channel_messages")
    # ### end Alembic commands ###
