"""add server channel foundation

Revision ID: b85a9ddfaf2b
Revises: 23330443a243
Create Date: 2026-05-04 16:11:15.396075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b85a9ddfaf2b"
down_revision: Union[str, Sequence[str], None] = "23330443a243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("owner_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_servers_slug"),
    )
    op.create_index(op.f("ix_servers_kind"), "servers", ["kind"], unique=False)
    op.create_index(
        op.f("ix_servers_owner_user_id"), "servers", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_servers_slug"), "servers", ["slug"], unique=False)
    op.create_table(
        "server_channels",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("visibility", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "server_id", "slug", name="uq_server_channels_server_id_slug"
        ),
    )
    op.create_index(
        op.f("ix_server_channels_created_by"),
        "server_channels",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channels_server_id"),
        "server_channels",
        ["server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channels_slug"), "server_channels", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_server_channels_visibility"),
        "server_channels",
        ["visibility"],
        unique=False,
    )
    op.create_table(
        "server_invites",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "max_uses", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "used_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_server_invites_token"),
    )
    op.create_index(
        op.f("ix_server_invites_created_by"),
        "server_invites",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_invites_server_id"),
        "server_invites",
        ["server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_invites_token"), "server_invites", ["token"], unique=False
    )
    op.create_table(
        "server_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invited_by", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "server_id", "user_id", name="uq_server_members_server_id_user_id"
        ),
    )
    op.create_index(
        op.f("ix_server_members_server_id"),
        "server_members",
        ["server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_members_user_id"), "server_members", ["user_id"], unique=False
    )
    op.create_table(
        "server_channel_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["server_channels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel_id", "user_id", name="uq_server_channel_members_channel_id_user_id"
        ),
    )
    op.create_index(
        op.f("ix_server_channel_members_channel_id"),
        "server_channel_members",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_server_channel_members_user_id"),
        "server_channel_members",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_server_channel_members_user_id"), table_name="server_channel_members"
    )
    op.drop_index(
        op.f("ix_server_channel_members_channel_id"),
        table_name="server_channel_members",
    )
    op.drop_table("server_channel_members")
    op.drop_index(op.f("ix_server_members_user_id"), table_name="server_members")
    op.drop_index(op.f("ix_server_members_server_id"), table_name="server_members")
    op.drop_table("server_members")
    op.drop_index(op.f("ix_server_invites_token"), table_name="server_invites")
    op.drop_index(op.f("ix_server_invites_server_id"), table_name="server_invites")
    op.drop_index(op.f("ix_server_invites_created_by"), table_name="server_invites")
    op.drop_table("server_invites")
    op.drop_index(op.f("ix_server_channels_visibility"), table_name="server_channels")
    op.drop_index(op.f("ix_server_channels_slug"), table_name="server_channels")
    op.drop_index(op.f("ix_server_channels_server_id"), table_name="server_channels")
    op.drop_index(op.f("ix_server_channels_created_by"), table_name="server_channels")
    op.drop_table("server_channels")
    op.drop_index(op.f("ix_servers_slug"), table_name="servers")
    op.drop_index(op.f("ix_servers_owner_user_id"), table_name="servers")
    op.drop_index(op.f("ix_servers_kind"), table_name="servers")
    op.drop_table("servers")
    # ### end Alembic commands ###
